/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.3/userguide/building_java_projects.html
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    id("org.sonarqube").version("3.1.1")
}

sonarqube {
    properties {
        property("sonar.projectKey", "SR-Lut3t1um_Multiuser-Lichess-Bot")
        property("sonar.organization", "sr-lut3t1um")
        property("sonar.host.url", "https://sonarcloud.io")
    }
}

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(16))
    }

}

repositories {
    // Use JCenter for resolving dependencies.
    mavenCentral()
    maven(url = "https://jitpack.io")
}

dependencies {
    // Use JUnit Jupiter API for testing.
    testImplementation("org.junit.jupiter:junit-jupiter-api:5.7.1")

    // Use JUnit Jupiter Engine for testing.
    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:30.1.1-jre")

    // This dependency is used to work with json.
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.2")

    // This dependency is used to check if a chess move is legal.
    implementation("com.github.bhlangonijr:chesslib:1.2.5")
}

application {
    // Define the main class for the application.
    mainClass.set("multiuser.lichess.bot.App")
}

tasks.test {
    // Use junit platform for unit tests.
    useJUnitPlatform()
}
