/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multiuser.lichess.bot;

import multiuser.lichess.bot.lichess_bot.LichessBot;
import multiuser.lichess.bot.lichess_bot.LichessGameManager;

public class App {

	static Thread.UncaughtExceptionHandler h = new Thread.UncaughtExceptionHandler() {
		@Override
		public void uncaughtException(Thread th, Throwable ex) {
			System.out.println("Thread with id:" + th.getId() + " crashed due to Uncaught exception: " + ex);
		}
	};

	/**
	 * The delay that shall be waited after retrying an api request.
	 */
  public static void main(String[] args) throws InterruptedException {
	  System.out.println("begin Startup");

	  LichessGameManager lichessGameManager = new LichessGameManager();
	  LichessBot lichessBot = new LichessBot();

	  var lichessGameManagerThread = new Thread( () -> {
	  	try {
	  		lichessGameManager.setup();
		  } catch (InterruptedException e) {
			  System.out.println("Interrupted Thread: " + Thread.currentThread().getId());
			  Thread.currentThread().interrupt();
		  } catch (Exception e) {
	  		throw new RuntimeException(e);
		  }}
	  );

	  lichessGameManagerThread.setUncaughtExceptionHandler(h);
	  lichessGameManagerThread.start();
	  lichessGameManagerThread.join();
  }
}
