/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package multiuser.lichess.bot;

import multiuser.lichess.bot.lichess_bot.LichessGameManager;
import org.tinylog.Logger;

public class App {

	private static final Thread.UncaughtExceptionHandler h = (th, ex) ->
			Logger.error("Thread with id:" + th.getId() + " crashed due to Uncaught exception: " + ex);

	/**
	 * The delay that shall be waited after retrying an api request.
	 */
	public static void main(String[] args) throws InterruptedException {
		Logger.info("begin Startup");

		LichessGameManager lichessGameManager = new LichessGameManager();

		var lichessGameManagerThread = new Thread(() -> {
			try {
				lichessGameManager.setup();
			} catch (InterruptedException e) {
				Logger.warn("Interrupted Thread: " + Thread.currentThread().getId());
				Thread.currentThread().interrupt();
			}
		}
		);

		lichessGameManagerThread.setUncaughtExceptionHandler(h);
		lichessGameManagerThread.start();
		lichessGameManagerThread.join();
	}
}
