/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Multiuser.Lichess.Bot;

import Multiuser.Lichess.Bot.Game.Game;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Game game = new Game();
        game.startGame(true);
    }
}
